server:
  port: 9002
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: intec-123
#    keyStoreType: PKCS12
#    keyAlias: tomcat

spring:
  application:
    name: cloud-discovery

  output:
    ansi:
      enabled: DETECT

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:9002/eureka/"
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true

